name: Deployment-of-python-app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "this job is runninf on ${{ runner.os }} server hosted on github!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python –m pip install –-upgrade pip
          pip install pylint
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Build Container Image
        run: |
          echo "Building a container image..."
          sleep 30
          echo "Container built successfully!"
      - name: Deploy to cluster
        run: |
          echo "Deploying to web cluster using rolling deployment..."
          sleep 30
          echo "🎉 App has been deployed successfully!"
      - run: echo "This job's status is ${{ job.status }}."          
     
