name: Deployment-of-python-app
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this has been triggered ${{ github.event_name }} event"
    - run: echo "This job is running on ${{ runner.os }} server hosted on github!"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Build container
      run: |
        echo "Building a container image..."
        sleep 30
											  
    - name: Deploy to cluster
      run: |
        echo "Deploying to cluster..."
        sleep 30
        echo "Container has been deployed!"
    - run: echo "This job's status is ${{ job.status }}."
	 
