name: build python app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - run: "python –m pip install –upgrade pip"
      - run: "pip install pylint"
